language: node_js
node_js:
  - lts/*
cache: npm
script:
  - npm run build
notifications:
  email:
    recipients:
      - just4ink007@gmail.com
    on_success: never
    on_failure: always
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: $AWS_REGION
  bucket: weather.thinkty.net
  skip_cleanup: true
  local_dir: build